# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-27 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picxp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='tags',
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to='pictures/'),
        ),
    ]
