# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-28 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picxp', '0002_auto_20200527_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='tags',
            field=models.ManyToManyField(to='picxp.tags'),
        ),
    ]
